name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  test:
    name: Test (Go)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          # Use latest stable to avoid invalid go directive issues
          go-version: stable
          cache: true

      - name: Go version
        run: go version

      - name: Download deps
        run: go mod download

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... -race -covermode=atomic -coverprofile=coverage.out

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: coverage
          path: coverage.out
